version: '3.7'
services:
  mysql:
    image: mysql
    container_name: phonebook-database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: phonebook
      MYSQL_USER: hitesh
      MYSQL_PASSWORD: hitesh
    volumes:
      - phonebook:/var/lib/mysql
    networks:
      - phonebook

  flask-home:
    build: 
      context: app/home
    container_name: phonebook-home
    image: devopshitesh/phonebook-home
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    networks:
      - phonebook
    environment:
      FLASK_ENV: development
      REGISTER_SERVICE_URL: /add_contact
      DELETION_SERVICE_URL: /view_contacts
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  flask-register:
    build:
      context: app/register
    container_name: phonebook-register
    image: devopshitesh/phonebook-register
    ports:
      - "5001:5001"
    depends_on:
      - mysql
      - flask-home
    networks:
      - phonebook
    environment:
      HOME_SERVICE_URL: /
      MYSQL_HOST: phonebook-database
      MYSQL_USER: hitesh
      MYSQL_PASSWORD: hitesh
      MYSQL_DB: phonebook
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001/"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  flask-deletion:
    build:
      context: app/deletion
    container_name: phonebook-deletion
    image: devopshitesh/phonebook-deletion
    ports:
      - "5002:5002"
    depends_on:
      - mysql
      - flask-home
      - flask-register
    networks:
      - phonebook
    environment:
      HOME_SERVICE_URL: /
      DELETE_SERVICE_URL: /delete_contact
      MYSQL_HOST: phonebook-database
      MYSQL_USER: hitesh
      MYSQL_PASSWORD: hitesh
      MYSQL_DB: phonebook
      MYSQL_CURSORCLASS: DictCursor
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5002"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  nginx:
    build: 
      context: nginx
    container_name: nginx
    image: devopshitesh/phonebook-nginx
    ports:
      - "80:80"
    depends_on:
      - mysql
      - flask-home
      - flask-register
    networks:
      - phonebook
    restart: always

networks:
  phonebook:

volumes:
  phonebook: